// <auto-generated />
using System;
using HochwaertsBibliothek2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HochwaertsBibliothek2.Migrations
{
    [DbContext(typeof(BibliothekDbContext))]
    partial class BibliothekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Ausleihe", b =>
                {
                    b.Property<int>("AusleiheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AusleiheId"));

                    b.Property<DateTime>("AusleihDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("AusleiherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExemplarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LetzteMahnungAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mahnstufe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RueckgabeDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("AusleiheId");

                    b.HasIndex("ExemplarId");

                    b.ToTable("Ausleihen");

                    b.HasData(
                        new
                        {
                            AusleiheId = 9001,
                            AusleihDatum = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            AusleiherName = "Max Mustermann",
                            ExemplarId = 103,
                            Mahnstufe = 0
                        },
                        new
                        {
                            AusleiheId = 9002,
                            AusleihDatum = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            AusleiherName = "Erika Beispiel",
                            ExemplarId = 402,
                            Mahnstufe = 0
                        },
                        new
                        {
                            AusleiheId = 9003,
                            AusleihDatum = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            AusleiherName = "Tim Test",
                            ExemplarId = 1201,
                            Mahnstufe = 0
                        });
                });

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Buch", b =>
                {
                    b.Property<int>("BuchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuchId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Erscheinungsjahr")
                        .HasColumnType("int");

                    b.Property<string>("Inhalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Klappentext")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BuchId");

                    b.HasIndex("Isbn");

                    b.ToTable("Buecher");

                    b.HasData(
                        new
                        {
                            BuchId = 1,
                            Autor = "Irma Pince",
                            Erscheinungsjahr = 2021,
                            Isbn = "978-0000000001",
                            Klappentext = "Ein Leitfaden für relationale Magie in Tabellenform.",
                            Titel = "Zauberhafte Datenbanken"
                        },
                        new
                        {
                            BuchId = 2,
                            Autor = "Prof. Wandermann",
                            Erscheinungsjahr = 2023,
                            Isbn = "978-0000000002",
                            Klappentext = "Model, View, Controller – ganz ohne Zauberstab.",
                            Titel = "MVC für Muggel"
                        },
                        new
                        {
                            BuchId = 3,
                            Autor = "Eleonore Federkiel",
                            Erscheinungsjahr = 2020,
                            Isbn = "978-0000000003",
                            Klappentext = "Zustände elegant verwalten: Ausleihbar bis Verkaufbar.",
                            Titel = "Buchstabeneulen & Bibliothekslogik"
                        },
                        new
                        {
                            BuchId = 4,
                            Autor = "Klaus Spellman",
                            Erscheinungsjahr = 2024,
                            Isbn = "978-0000000004",
                            Klappentext = "C#-Zaubertricks für sauberen Code.",
                            Titel = "Hexenwerk mit C#"
                        },
                        new
                        {
                            BuchId = 5,
                            Autor = "Ilias Ink",
                            Erscheinungsjahr = 2022,
                            Isbn = "978-0000000005",
                            Klappentext = "Fristen, Erinnerungen und Ordnung in der Bibliothek.",
                            Titel = "Die Kunst der Mahnung"
                        },
                        new
                        {
                            BuchId = 6,
                            Autor = "Stefan Müller",
                            Erscheinungsjahr = 2025,
                            Isbn = "978-0000000006",
                            Klappentext = "UI, das nach Hochwärts aussieht – ohne CSS-Schmerz.",
                            Titel = "Bootstrap & Bannergold"
                        },
                        new
                        {
                            BuchId = 7,
                            Autor = "Valeria Wurm",
                            Erscheinungsjahr = 2021,
                            Isbn = "978-0000000007",
                            Klappentext = "Code-First, Migrationen und magische Daten.",
                            Titel = "EF Core Codex"
                        },
                        new
                        {
                            BuchId = 8,
                            Autor = "Robin Rot",
                            Erscheinungsjahr = 2019,
                            Isbn = "978-0000000008",
                            Klappentext = "Kurzgeschichten aus dem Roten Haus.",
                            Titel = "Die Leseratte liest"
                        },
                        new
                        {
                            BuchId = 9,
                            Autor = "Bruno Grün",
                            Erscheinungsjahr = 2018,
                            Isbn = "978-0000000009",
                            Klappentext = "Geschichten für lange Winterabende.",
                            Titel = "Vorlesebär Bruno"
                        },
                        new
                        {
                            BuchId = 10,
                            Autor = "Archiv Hochwärts",
                            Erscheinungsjahr = 2017,
                            Isbn = "978-0000000010",
                            Klappentext = "Von ERM bis PK/FK – Grundlagen der Ordnung.",
                            Titel = "Zauberschule der Tabellen"
                        },
                        new
                        {
                            BuchId = 11,
                            Autor = "Bibliotheksrat",
                            Erscheinungsjahr = 2016,
                            Isbn = "978-0000000011",
                            Klappentext = "Wenn der Text hinten besser ist als vorne.",
                            Titel = "Das große Klappentext-Kompendium"
                        },
                        new
                        {
                            BuchId = 12,
                            Autor = "Eleonore Federkiel",
                            Erscheinungsjahr = 2022,
                            Isbn = "978-0000000012",
                            Klappentext = "Use Cases, Klassen, Zustände – verständlich.",
                            Titel = "Eule Eleonore erklärt UML"
                        });
                });

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Exemplar", b =>
                {
                    b.Property<int>("ExemplarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExemplarId"));

                    b.Property<int>("Beschädigung")
                        .HasColumnType("int");

                    b.Property<int>("BuchId")
                        .HasColumnType("int");

                    b.Property<string>("InventarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerschollenSeit")
                        .HasColumnType("datetime2");

                    b.HasKey("ExemplarId");

                    b.HasIndex("BuchId");

                    b.ToTable("Exemplare");

                    b.HasData(
                        new
                        {
                            ExemplarId = 101,
                            Beschädigung = 0,
                            BuchId = 1,
                            InventarCode = "HW-DB-101",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 102,
                            Beschädigung = 4,
                            BuchId = 1,
                            InventarCode = "HW-DB-102",
                            Status = 4
                        },
                        new
                        {
                            ExemplarId = 103,
                            Beschädigung = 1,
                            BuchId = 1,
                            InventarCode = "HW-DB-103",
                            Status = 1
                        },
                        new
                        {
                            ExemplarId = 201,
                            Beschädigung = 0,
                            BuchId = 2,
                            InventarCode = "HW-MVC-201",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 202,
                            Beschädigung = 2,
                            BuchId = 2,
                            InventarCode = "HW-MVC-202",
                            Status = 2
                        },
                        new
                        {
                            ExemplarId = 301,
                            Beschädigung = 1,
                            BuchId = 3,
                            InventarCode = "HW-LOG-301",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 302,
                            Beschädigung = 4,
                            BuchId = 3,
                            InventarCode = "HW-LOG-302",
                            Status = 4
                        },
                        new
                        {
                            ExemplarId = 401,
                            Beschädigung = 0,
                            BuchId = 4,
                            InventarCode = "HW-CS-401",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 402,
                            Beschädigung = 0,
                            BuchId = 4,
                            InventarCode = "HW-CS-402",
                            Status = 1
                        },
                        new
                        {
                            ExemplarId = 501,
                            Beschädigung = 0,
                            BuchId = 5,
                            InventarCode = "HW-MAH-501",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 502,
                            Beschädigung = 3,
                            BuchId = 5,
                            InventarCode = "HW-MAH-502",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 601,
                            Beschädigung = 1,
                            BuchId = 6,
                            InventarCode = "HW-BS-601",
                            Status = 2
                        },
                        new
                        {
                            ExemplarId = 602,
                            Beschädigung = 0,
                            BuchId = 6,
                            InventarCode = "HW-BS-602",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 701,
                            Beschädigung = 0,
                            BuchId = 7,
                            InventarCode = "HW-EF-701",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 702,
                            Beschädigung = 2,
                            BuchId = 7,
                            InventarCode = "HW-EF-702",
                            Status = 3,
                            VerschollenSeit = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ExemplarId = 801,
                            Beschädigung = 0,
                            BuchId = 8,
                            InventarCode = "HW-ROT-801",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 901,
                            Beschädigung = 4,
                            BuchId = 9,
                            InventarCode = "HW-GRN-901",
                            Status = 4
                        },
                        new
                        {
                            ExemplarId = 1001,
                            Beschädigung = 0,
                            BuchId = 10,
                            InventarCode = "HW-ERM-1001",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 1101,
                            Beschädigung = 0,
                            BuchId = 11,
                            InventarCode = "HW-KT-1101",
                            Status = 0
                        },
                        new
                        {
                            ExemplarId = 1201,
                            Beschädigung = 1,
                            BuchId = 12,
                            InventarCode = "HW-UML-1201",
                            Status = 1
                        },
                        new
                        {
                            ExemplarId = 1202,
                            Beschädigung = 0,
                            BuchId = 12,
                            InventarCode = "HW-UML-1202",
                            Status = 0
                        });
                });

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Ausleihe", b =>
                {
                    b.HasOne("HochwaertsBibliothek2.Models.Exemplar", "Exemplar")
                        .WithMany("Ausleihen")
                        .HasForeignKey("ExemplarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exemplar");
                });

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Exemplar", b =>
                {
                    b.HasOne("HochwaertsBibliothek2.Models.Buch", "Buch")
                        .WithMany("Exemplare")
                        .HasForeignKey("BuchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buch");
                });

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Buch", b =>
                {
                    b.Navigation("Exemplare");
                });

            modelBuilder.Entity("HochwaertsBibliothek2.Models.Exemplar", b =>
                {
                    b.Navigation("Ausleihen");
                });
#pragma warning restore 612, 618
        }
    }
}
